# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [1]:
import torch

In [2]:
# ваш код здесь
import torch
print(torch.__version__)

2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# ваш код здесь
v = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
tensor = torch.tensor(v)
print(
    f"{tensor}",
    sep="\n\n")

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [4]:
# ваш код здесь
print(
    f"Тип элементов:\n{tensor.dtype}",
    f"Размер:\n{tensor.shape}",
    f"Кол-во размерностей:\n{tensor.dim()}",
    sep="\n\n"
)

Тип элементов:
torch.int64

Размер:
torch.Size([10])

Кол-во размерностей:
1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [5]:
# ваш код здесь
print(f"Левая часть:\n {tensor[:5]}")

print(f"Правая часть:\n {tensor[5:10]}")


Левая часть:
 tensor([0, 1, 2, 3, 4])
Правая часть:
 tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [6]:
# ваш код здесь

torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [7]:
# ваш код здесь
torch.ones(5,2,dtype=torch.bool)


tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [17]:
# ваш код здесь
torch.arange(1, 15.5, 0.5, dtype=torch.double)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000], dtype=torch.float64)

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [19]:
# ваш код здесь
torch.linspace(1, 10, 20, dtype=torch.float64)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000], dtype=torch.float64)

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [21]:
# ваш код здесь
torch.rand(4, 3, dtype=torch.float32)

tensor([[0.1266, 0.1915, 0.9044],
        [0.5728, 0.8791, 0.0606],
        [0.2726, 0.6471, 0.0066],
        [0.1446, 0.4691, 0.0612]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [41]:
# ваш код здесь
school=torch.randint(3, 6, (100,), dtype=torch.float32)
print(school)

tensor([5., 5., 4., 3., 3., 4., 3., 4., 4., 4., 4., 5., 4., 5., 3., 5., 3., 5.,
        4., 3., 5., 4., 4., 3., 5., 4., 4., 3., 4., 3., 5., 5., 4., 5., 3., 4.,
        4., 5., 3., 4., 3., 3., 4., 4., 3., 5., 3., 5., 3., 5., 4., 4., 4., 3.,
        3., 5., 4., 5., 5., 4., 5., 4., 3., 3., 3., 4., 3., 3., 4., 5., 5., 4.,
        5., 5., 4., 3., 5., 5., 3., 3., 3., 3., 3., 4., 4., 5., 5., 4., 3., 3.,
        5., 3., 4., 3., 4., 4., 3., 3., 5., 4.])


Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [43]:
# ваш код здесь
print(
    f"Максимальное значение: \n{school.max()}",
    f"Минимально значение: \n{school.min()}",
    f"Среднее значение: \n{school.mean()}",
    sep = "\n\n",
      )

Максимальное значение: 
5.0

Минимально значение: 
3.0

Среднее значение: 
3.940000057220459


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [47]:
# ваш код здесь
mask = torch.zeros_like(school, dtype=torch.bool)
mask[:5] = True
mask[95:100] = True
print(mask)

tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [54]:
# ваш код здесь
filt = school[mask]
print(filt)

tensor([5., 5., 4., 3., 3., 4., 3., 3., 5., 4.])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [55]:
# ваш код здесь
five = school == 5
print(five)

tensor([ True,  True, False, False, False, False, False, False, False, False,
        False,  True, False,  True, False,  True, False,  True, False, False,
         True, False, False, False,  True, False, False, False, False, False,
         True,  True, False,  True, False, False, False,  True, False, False,
        False, False, False, False, False,  True, False,  True, False,  True,
        False, False, False, False, False,  True, False,  True,  True, False,
         True, False, False, False, False, False, False, False, False,  True,
         True, False,  True,  True, False, False,  True,  True, False, False,
        False, False, False, False, False,  True,  True, False, False, False,
         True, False, False, False, False, False, False, False,  True, False])


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [56]:
# ваш код здесь
new = school[five]
print(new)

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [57]:
# ваш код здесь
preobr = school.reshape(5,20)
print(preobr)

tensor([[5., 5., 4., 3., 3., 4., 3., 4., 4., 4., 4., 5., 4., 5., 3., 5., 3., 5.,
         4., 3.],
        [5., 4., 4., 3., 5., 4., 4., 3., 4., 3., 5., 5., 4., 5., 3., 4., 4., 5.,
         3., 4.],
        [3., 3., 4., 4., 3., 5., 3., 5., 3., 5., 4., 4., 4., 3., 3., 5., 4., 5.,
         5., 4.],
        [5., 4., 3., 3., 3., 4., 3., 3., 4., 5., 5., 4., 5., 5., 4., 3., 5., 5.,
         3., 3.],
        [3., 3., 3., 4., 4., 5., 5., 4., 3., 3., 5., 3., 4., 3., 4., 4., 3., 3.,
         5., 4.]])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [88]:
# ваш код здесь
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
a1 = a.repeat(1, 3)[:, :5]
vniz = torch.cat([a1, b], dim = 0)
print(vniz)

tensor([[2., 4., 2., 4., 2.],
        [6., 8., 6., 8., 6.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [102]:
# ваш код здесь
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
vpravo = torch.cat([a, b], dim = 1)
print(vpravo)

tensor([[2., 4., 1., 1., 1., 1., 1.],
        [6., 8., 1., 1., 1., 1., 1.]])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [84]:
# ваш код здесь
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (5 <= a) & (a <= 10)
otr = a[mask]
print(otr)

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [103]:
# ваш код здесь
print(vpravo[0, :])

tensor([2., 4., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [106]:
# ваш код здесь
print(vniz[:, 4])

tensor([2., 6., 1., 1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [95]:
# ваш код здесь
print(vniz[1:3, 1:4])

tensor([[8., 6., 8.],
        [1., 1., 1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [98]:
# ваш код здесь
min = vniz.min()
row = torch.full((1, vniz.shape[1]), min)
otvet = torch.cat([row, vniz], dim=0)
print(otvet)

tensor([[1., 1., 1., 1., 1.],
        [2., 4., 2., 4., 2.],
        [6., 8., 6., 8., 6.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [99]:
# ваш код здесь
print(otvet.sqrt())

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 2.0000, 1.4142, 2.0000, 1.4142],
        [2.4495, 2.8284, 2.4495, 2.8284, 2.4495],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [104]:
# ваш код здесь
mask1 = (vpravo % 2 == 0) | (vpravo % 3 == 0)
vpravo[mask1] = 1
print(vpravo)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
